server:
  port: 7000


spring:
  #  profiles:
  #    active: dev
  application:
    name: gulimall-coupon
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml,classpath:/META-INF/modeler-mybatis-mappings/*.xml
  global-config:
    db-config:
      id-type: AUTO

coupon:
  user:
    name: void123
    age: 25123

